### check root / for api up message

GET http://localhost:5000

### get a list of users
GET http://localhost:5000/users

### create a user account

POST http://localhost:5000/users
Content-Type: application/json

{
  "username": "edmadrigal",
  "password": "password123"
}
### check login
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "edmadrigal",
  "password": "password123"
}